apiVersion: v1
kind: Secret
metadata:
  name: clearml-credentials
  namespace: default
type: Opaque
data:
  api_key: bWxfYXBpX2tleV9kZXRlcm1pbmF0aW9u
  api_secret: bWxfYXBpX3NlY3JldF9kZXRlcm1pbmF0aW9u

apiVersion: v1
kind: Secret
metadata:
  name: clearml-credentials
  namespace: default
type: Opaque
stringData:
  api_key: "mlapi_AUTO_GENERATED_KEY_12345"
  api_secret: "mlapi_AUTO_GENERATED_SECRET_abcdEFGH"
